### ISSUE TITLE
Question on input

### ISSUE THREAD

**Issue by Lancelot-Ac** [rdellamonica/Yukawa-S2#1]
Hi~

Thanks for your attention.

When running the code, three values of `lamb`, `delta` and `M` are needed to input. Are they the initial guesses of lambda, delta and the mass of BH? I tried to insert values within a reasonable range, then I got a error report as:

```
Traceback (most recent call last):

  File "C:\Users\Zhou\anaconda3\lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

TypeError: unhashable type: 'list'
```
I am not sure if it is due to the software version? The python version is 3.8.3 and the PyGRO version is 0.0.8.

In addition, there seems a typo in line 239, the first element of `delta_params` should be `0.012*1e+6*Msun` instead of  `0.012*1e+6**Msun`.

**Comment by rdellamonica** [comment]
Dear user,

Thanks for your message.

> When running the code, three values of lamb, delta and M are needed to input....

The `Metric()` object in PyGRO 0.0.8 requires, upon initialisation of the metric tensor, to set the values for the constants that appear in the metric coefficients. Since, later in the code, the values of `delta` and `lamb` will be extracted from the MCMC sampler, you can set any value you wish. As for the mass `M`, its value should be set to unity in order to have all quantity expressed in geometrical units. Anyway, the previous versions of PyGRO (that was the one for which this code was written) didn't require the user to set initial values for the parameters, so this problem was not present in the original version of the code.

> In addition, there seems a typo in line 239,...

Yes. Thank you, this is indeed a typo that was solved in the final version of the code, but that was never committed here on Github.

Anyway, I have committed a new version of the code to overcome this issues and that is fully compatible with the new version of PyGRO, also in terms of parameters of the Runge-Kutta integrator that now works differently with respect to older versions. 

If you have any doubt, please don't hesitate to ask.

Riccardo
